name: "CI"

on:
  push: {branches: master}
  pull_request: {branches: master}
  repository_dispatch:

jobs:
  job_1:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        npm ci
        npm run all
    - name: Use coturiv/setup-ionic
      uses: ./
    - name: Run cordova project tests
      run: |
        ionic info
        ionic start testapp blank --cordova --type angular --no-link --no-git --no-interactive --confirm
        cd testapp
        ionic cordova platform add android@latest
        ionic cordova build android
